export const features = [
  {
    id: 1,
    url: "https://images.meesho.com/images/products/19403589/rladh_400.webp",
    title: "Mens causal Wear",
    description: "30%-60% offer",
  },
  {
    id: 2,
    url: "https://images.meesho.com/images/products/485621590/pnrwa_400.webp",
    title: "Mens Wear",
    description: "20%-60% offer",
  },
  {
    id: 3,
    url: "https://images.meesho.com/images/products/458445578/lxp44_400.webp",
    title: "Womens causal Wear",
    description: "40%-80% offer",
  },
  {
    id: 4,
    url: "https://images.meesho.com/images/products/382519791/yzcii_400.webp",
    title: "Womens Wear",
    description: "30%-60% offer",
  },
  {
    id: 5,
    url: "https://images.meesho.com/images/products/377881236/b3m6u_400.webp",
    title: "Skincare",
    description: "30%-60% offer",
  },
];

export const productCategory = [
  {
    id: 1,
    url: "https://images.meesho.com/images/marketing/1744634780426.webp",
    title: "Mens",
    navigateurl: "/category/mens",
  },
  {
    id: 2,
    url: "https://images.meesho.com/images/marketing/1744634654837.webp",
    title: "Womens",
    navigateurl: "/category/womens",
  },
  {
    id: 3,
    url: "https://images.meesho.com/images/marketing/1744634814643.webp",
    title: "Footwear",
    navigateurl: "/category/footwear",
  },
  {
    id: 4,
    url: "https://images.meesho.com/images/marketing/1744634871107.webp",
    title: "Beauty",
    navigateurl: "/category/beauty",
  },
  {
    id: 5,
    url: "https://images.meesho.com/images/marketing/1744634909968.webp",
    title: "Bags",
    navigateurl: "/category/accessories",
  },
];

export const womens = [
  {
    id: 1,
    url: "https://images.meesho.com/images/products/458445578/lxp44_400.webp",
    title: "Jivika Pretty Sarees",
    price: "$424",
    deliveryStatus: "Free Delivery",
    reviews: "3432",
    ratings: "3.4",
  },
  {
    id: 2,
    url: "https://images.meesho.com/images/products/386329438/1bjhj_400.webp",
    title: "Puff Sleeve Kurti ",
    price: "$524",
    deliveryStatus: "Free Delivery",
    reviews: "2333",
    ratings: "4.4",
  },
  {
    id: 3,
    url: "https://images.meesho.com/images/products/149834633/saqqo_400.webp",
    title: "Anarkali Kurti",
    price: "$374",
    deliveryStatus: "Free Delivery",
    reviews: "234",
    ratings: "3.4",
  },
  {
    id: 4,
    url: "https://images.meesho.com/images/products/382519791/yzcii_400.webp",
    title: "Floral design Kurtis",
    price: "$624",
    deliveryStatus: "Free Delivery",
    reviews: "232",
    ratings: "3.4",
  },
  {
    id: 5,
    url: "https://images.meesho.com/images/products/384983175/fhgox_400.webp",
    title: "Trendy Short Top",
    price: "$454",
    deliveryStatus: "Free Delivery",
    reviews: "32432",
    ratings: "3.4",
  },
  {
    id: 6,
    url: "https://images.meesho.com/images/products/376569826/b3rql_400.webp",
    title: "Trendy Gown",
    price: "$734",
    deliveryStatus: "Free Delivery",
    reviews: "332",
    ratings: "3.4",
  },
  {
    id: 7,
    url: "https://images.meesho.com/images/products/399022460/c5ikm_400.webp",
    title: "Latest treandy tops with coat",
    price: "$324",
    deliveryStatus: "Free Delivery",
    reviews: "34",
    ratings: "3.4",
  },
  {
    id: 8,
    url: "https://images.meesho.com/images/products/191005346/mocgn_400.webp",
    title: "Western kurti with pant",
    price: "$373",
    deliveryStatus: "Free Delivery",
    reviews: "76768",
    ratings: "3.4",
  },
  {
    id: 9,
    url: "https://images.meesho.com/images/products/393333484/kbovs_400.webp",
    title: "Latest treandy tops with coat",
    price: "$324",
    deliveryStatus: "Free Delivery",
    reviews: "7679",
    ratings: "3.4",
  },
  {
    id: 10,
    url: "https://images.meesho.com/images/products/68464151/f1nit_400.webp",
    title: "Jivika Pretty Sarees",
    price: "$624",
    deliveryStatus: "Free Delivery",
    reviews: "898",
    ratings: "3.4",
  },
  {
    id: 11,
    url: "https://images.meesho.com/images/products/391297988/2rab5_400.webp",
    title: "Wetern Kurtis",
    price: "$424",
    deliveryStatus: "Free Delivery",
    reviews: "7782",
    ratings: "3.4",
  },
  {
    id: 12,
    url: "https://images.meesho.com/images/products/390607339/sulz0_400.webp",
    title: "Trendy Palozzo Sets",
    price: "$644",
    deliveryStatus: "Free Delivery",
    reviews: "8977",
    ratings: "3.4",
  },
];

export const mens = [
  {
    id: 1,
    url: "https://images.meesho.com/images/products/485621590/pnrwa_400.webp",
    title: "Causal T-shirt",
    price: "$324",
    deliveryStatus: "Free Delivery",
    reviews: "3756",
    ratings: "3.4",
  },
  {
    id: 2,
    url: "https://images.meesho.com/images/products/6585573/67517_400.webp",
    title: "Formal Mens Shirt",
    price: "$524",
    deliveryStatus: "Free Delivery",
    reviews: "346",
    ratings: "3.4",
  },
  {
    id: 3,
    url: "https://images.meesho.com/images/products/415995326/rrm1r_400.webp",
    title: "Fancy Mens Dhoti",
    price: "$324",
    deliveryStatus: "Free Delivery",
    reviews: "778",
    ratings: "3.4",
  },
  {
    id: 4,
    url: "https://images.meesho.com/images/products/1707198/1_400.webp",
    title: "Track Pants",
    price: "$524",
    deliveryStatus: "Free Delivery",
    reviews: "566",
    ratings: "3.4",
  },
  {
    id: 5,
    url: "https://images.meesho.com/images/products/44175508/bbvuf_400.webp",
    title: "Mens Causal Shirts",
    price: "$724",
    deliveryStatus: "Free Delivery",
    reviews: "664",
    ratings: "3.4",
  },
  {
    id: 6,
    url: "https://images.meesho.com/images/products/36477568/6l0jc_400.webp",
    title: "Urbane Mens t-shirt",
    price: "$424",
    deliveryStatus: "Free Delivery",
    reviews: "453",
    ratings: "3.4",
  },
  {
    id: 7,
    url: "https://images.meesho.com/images/products/27029586/8wbfn_400.webp",
    title: "Slim fit jeans",
    price: "$324",
    deliveryStatus: "Free Delivery",
    reviews: "78565",
    ratings: "3.4",
  },
  {
    id: 8,
    url: "https://images.meesho.com/images/products/19403589/rladh_400.webp",
    title: "Urbane Mens T-shirt",
    price: "$284",
    deliveryStatus: "Free Delivery",
    reviews: "57567",
    ratings: "3.4",
  },
  {
    id: 9,
    url: "https://images.meesho.com/images/products/54469196/v1ytc_400.webp",
    title: "Ethnic Wear",
    price: "$524",
    deliveryStatus: "Free Delivery",
    reviews: "3648",
    ratings: "3.4",
  },
  {
    id: 10,
    url: "https://images.meesho.com/images/products/8815696/6ra4y_400.webp",
    title: "Mens Causal Shirt",
    price: "$424",
    deliveryStatus: "Free Delivery",
    reviews: "8628",
    ratings: "3.4",
  },
  {
    id: 11,
    url: "https://images.meesho.com/images/products/5920831/yaykq_400.webp",
    title: "Ethnic Wear",
    price: "$524",
    deliveryStatus: "Free Delivery",
    reviews: "1336",
    ratings: "3.4",
  },
  {
    id: 12,
    url: "https://images.meesho.com/images/products/186274486/oidhk_400.webp",
    title: "Mens Trendy Shorts",
    price: "$224",
    deliveryStatus: "Free Delivery",
    reviews: "437",
    ratings: "3.4",
  },
];
