import { WEB_URL } from "api/urls";

export const features = [
  {
    id: "5461",
    url: "https://images.meesho.com/images/products/19403589/rladh_400.webp",
    title: "Mens causal Wear",
    description: "30%-60% offer",
  },
  {
    id: 5462,
    url: "https://images.meesho.com/images/products/485621590/pnrwa_400.webp",
    title: "Mens Wear",
    description: "20%-60% offer",
  },
  {
    id: 5463,
    url: "https://images.meesho.com/images/products/458445578/lxp44_400.webp",
    title: "Womens causal",
    description: "40%-80% offer",
  },
  {
    id: 5464,
    url: "https://images.meesho.com/images/products/382519791/yzcii_400.webp",
    title: "Womens Wear",
    description: "30%-60% offer",
  },
  {
    id: 5465,
    url: "https://images.meesho.com/images/products/377881236/b3m6u_400.webp",
    title: "Skincare",
    description: "30%-60% offer",
  },
];

export const productCategory = [
  {
    id: 5461,
    url: "https://images.meesho.com/images/marketing/1744634780426.webp",
    title: "Men",
    navigateurl: WEB_URL.PRODUCT.MEN,
  },
  {
    id: 5462,
    url: "https://images.meesho.com/images/marketing/1744634654837.webp",
    title: "Women",
    navigateurl: WEB_URL.PRODUCT.WOMEN,
  },
  {
    id: 5463,
    url: "https://images.meesho.com/images/marketing/1744634814643.webp",
    title: "Footwear",
    navigateurl: WEB_URL.PRODUCT.FOOTWEAR,
  },
  {
    id: 5464,
    url: "https://images.meesho.com/images/marketing/1744634871107.webp",
    title: "BeautyProducts",
    navigateurl: WEB_URL.PRODUCT.BEAUTY,
  },
  {
    id: 5465,
    url: "https://images.meesho.com/images/marketing/1744634909968.webp",
    title: "Bags",
    navigateurl: WEB_URL.PRODUCT.BAG,
  },
];

export const womens = [
  {
    id: "w-231",
    url: "https://images.meesho.com/images/products/458445578/lxp44_400.webp",
    title: "Jivika Pretty Sarees",
    price: 424,
    deliveryStatus: "Free Delivery",
    reviews: "3432",
    ratings: "3.4",
    category: ["Saree"],
    brand: "Zara",
  },
  {
    id: "w-232",
    url: "https://images.meesho.com/images/products/386329438/1bjhj_400.webp",
    title: "Puff Sleeve Kurti ",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "2333",
    ratings: "4.4",
    category: ["Kurti"],
    brand: "Nike",
  },
  {
    id: "w-233",
    url: "https://images.meesho.com/images/products/149834633/saqqo_400.webp",
    title: "Anarkali Kurti",
    price: 374,
    deliveryStatus: "Free Delivery",
    reviews: "234",
    ratings: "3.4",
    category: ["Kurti"],
    brand: "Adidas",
  },
  {
    id: "w-234",
    url: "https://images.meesho.com/images/products/382519791/yzcii_400.webp",
    title: "Floral design Kurtis",
    price: 624,
    deliveryStatus: "Free Delivery",
    reviews: "232",
    ratings: "3.4",
    category: ["Kurti"],
    brand: "Puma",
  },
  {
    id: "w-235",
    url: "https://images.meesho.com/images/products/384983175/fhgox_400.webp",
    title: "Trendy Short Top",
    price: 454,
    deliveryStatus: "Free Delivery",
    reviews: "32432",
    ratings: "3.4",
    category: ["Top"],
    brand: "Nike",
  },
  {
    id: "w-236",
    url: "https://images.meesho.com/images/products/376569826/b3rql_400.webp",
    title: "Trendy Gown",
    price: 734,
    deliveryStatus: "Free Delivery",
    reviews: "332",
    ratings: "3.4",
    category: ["Gown"],
    brand: "Adidas",
  },
  {
    id: "w-237",
    url: "https://images.meesho.com/images/products/399022460/c5ikm_400.webp",
    title: "Latest treandy tops with coat",
    price: 324,
    deliveryStatus: "Free Delivery",
    reviews: "34",
    ratings: "3.4",
    category: ["Top"],
    brand: "Zara",
  },
  {
    id: "w-238",
    url: "https://images.meesho.com/images/products/191005346/mocgn_400.webp",
    title: "Western kurti with pant",
    price: 373,
    deliveryStatus: "Free Delivery",
    reviews: "76768",
    ratings: "3.4",
    category: ["Kurti"],
    brand: "Puma",
  },
  {
    id: "w-239",
    url: "https://images.meesho.com/images/products/393333484/kbovs_400.webp",
    title: "Latest treandy tops with coat",
    price: 324,
    deliveryStatus: "Free Delivery",
    reviews: "7679",
    ratings: "3.4",
    category: ["Top"],
    brand: "Nike",
  },
  {
    id: "w-2310",
    url: "https://images.meesho.com/images/products/68464151/f1nit_400.webp",
    title: "Jivika Pretty Sarees",
    price: 624,
    deliveryStatus: "Free Delivery",
    reviews: "898",
    ratings: "3.4",
    category: ["Saree"],
    brand: "Adidas",
  },
  {
    id: "w-2311",
    url: "https://images.meesho.com/images/products/391297988/2rab5_400.webp",
    title: "Wetern Kurtis",
    price: 424,
    deliveryStatus: "Free Delivery",
    reviews: "7782",
    ratings: "3.4",
    category: ["Kurti"],
    brand: "Zara",
  },
  {
    id: "w-2312",
    url: "https://images.meesho.com/images/products/390607339/sulz0_400.webp",
    title: "Trendy Palozzo Sets",
    price: 644,
    deliveryStatus: "Free Delivery",
    reviews: "8977",
    ratings: "3.4",
    category: ["Palozzo Set"],
    brand: "Puma",
  },
];

export const mens = [
  {
    id: "m-331",
    url: "https://images.meesho.com/images/products/485621590/pnrwa_400.webp",
    title: "Causal T-shirt",
    price: 324,
    deliveryStatus: "Free Delivery",
    reviews: "3756",
    ratings: "3.4",
    category: ["T-Shirts"],
    brand: "Puma",
  },
  {
    id: "m-332",
    url: "https://images.meesho.com/images/products/6585573/67517_400.webp",
    title: "Formal Mens Shirt",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "346",
    ratings: "3.4",
    category: ["Shirts"],
    brand: "Nike",
  },
  {
    id: "m-333",
    url: "https://images.meesho.com/images/products/415995326/rrm1r_400.webp",
    title: "Fancy Mens Dhoti",
    price: 324,
    deliveryStatus: "Free Delivery",
    reviews: "778",
    ratings: "3.4",
    category: ["Dhoti"],
    brand: "Adidas",
  },
  {
    id: "m-334",
    url: "https://images.meesho.com/images/products/1707198/1_400.webp",
    title: "Track Pants",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "566",
    ratings: "3.4",
    category: ["Pants"],
    brand: "Zara",
  },
  {
    id: "m-335",
    url: "https://images.meesho.com/images/products/44175508/bbvuf_400.webp",
    title: "Mens Causal Shirts",
    price: 724,
    deliveryStatus: "Free Delivery",
    reviews: "664",
    ratings: "3.4",
    category: ["Shirts"],
    brand: "Puma",
  },
  {
    id: "m-336",
    url: "https://images.meesho.com/images/products/36477568/6l0jc_400.webp",
    title: "Urbane Mens t-shirt",
    price: 424,
    deliveryStatus: "Free Delivery",
    reviews: "453",
    ratings: "3.4",
    category: ["T-Shirts"],
    brand: "Nike",
  },
  {
    id: "m-337",
    url: "https://images.meesho.com/images/products/27029586/8wbfn_400.webp",
    title: "Slim fit jeans",
    price: 324,
    deliveryStatus: "Free Delivery",
    reviews: "78565",
    ratings: "3.4",
    category: ["Jeans"],
    brand: "Adidas",
  },
  {
    id: "m-338",
    url: "https://images.meesho.com/images/products/19403589/rladh_400.webp",
    title: "Urbane Mens T-shirt",
    price: 284,
    deliveryStatus: "Free Delivery",
    reviews: "57567",
    ratings: "3.4",
    category: ["T-Shirts"],
    brand: "Zara",
  },
  {
    id: "m-339",
    url: "https://images.meesho.com/images/products/54469196/v1ytc_400.webp",
    title: "Ethnic Wear",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "3648",
    ratings: "3.4",
    category: ["Ethnic Wear"],
    brand: "Puma",
  },
  {
    id: "m-3310",
    url: "https://images.meesho.com/images/products/8815696/6ra4y_400.webp",
    title: "Mens Causal Shirt",
    price: 424,
    deliveryStatus: "Free Delivery",
    reviews: "8628",
    ratings: "3.4",
    category: ["Shirts"],
    brand: "Nike",
  },
  {
    id: "m-3311",
    url: "https://images.meesho.com/images/products/5920831/yaykq_400.webp",
    title: "Ethnic Wear",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "1336",
    ratings: "3.4",
    category: ["Ethnic Wear"],
    brand: "Adidas",
  },
  {
    id: "m-3312",
    url: "https://images.meesho.com/images/products/186274486/oidhk_400.webp",
    title: "Mens Trendy Shorts",
    price: 224,
    deliveryStatus: "Free Delivery",
    reviews: "437",
    ratings: "3.4",
    category: ["Shorts"],
    brand: "Zara",
  },
];

export const footwear = [
  {
    id: "f-441",
    url: "https://images.meesho.com/images/products/489183933/0b3hy_400.webp",
    title: "Womens trendy Sandals",
    price: 324,
    deliveryStatus: "Free Delivery",
    reviews: "3756",
    ratings: "3.4",
    category: ["Sandals"],
    brand: "Paragon",
  },
  {
    id: "f-442",
    url: "https://images.meesho.com/images/products/266882199/3xl12_400.webp",
    title: "Formal Mens Shoes",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "346",
    ratings: "3.4",
    category: ["Shoes"],
    brand: "Liberty",
  },
  {
    id: "f-443",
    url: "https://images.meesho.com/images/products/427376570/s6yrb_400.webp",
    title: "Fancy kids sandals",
    price: 324,
    deliveryStatus: "Free Delivery",
    reviews: "778",
    ratings: "3.4",
    category: ["Kids", "Sandals"],
    brand: "Relaxo",
  },
  {
    id: "f-444",
    url: "https://images.meesho.com/images/products/41816149/8ioys_400.webp",
    title: "Sandals",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "566",
    ratings: "3.4",
    category: ["Sandals"],
    brand: "Bata",
  },
  {
    id: "f-445",
    url: "https://images.meesho.com/images/products/137626314/zyscv_400.webp",
    title: "Mens Causal Sandals",
    price: 724,
    deliveryStatus: "Free Delivery",
    reviews: "664",
    ratings: "3.4",
    category: ["Sandals"],
    brand: "Paragon",
  },
  {
    id: "f-446",
    url: "https://images.meesho.com/images/products/370528537/mczok_400.webp",
    title: "Sports Shoes",
    price: 424,
    deliveryStatus: "Free Delivery",
    reviews: "453",
    ratings: "3.4",
    category: ["Sports Shoes"],
    brand: "Liberty",
  },
  {
    id: "f-447",
    url: "https://images.meesho.com/images/products/523781120/janed_400.webp",
    title: "Sandals",
    price: 324,
    deliveryStatus: "Free Delivery",
    reviews: "78565",
    ratings: "3.4",
    category: ["Sandals"],
    brand: "Relaxo",
  },
  {
    id: "f-448",
    url: "https://images.meesho.com/images/products/332463695/woduf_400.webp",
    title: "Womens Fashionable Footwer",
    price: 284,
    deliveryStatus: "Free Delivery",
    reviews: "57567",
    ratings: "3.4",
    category: ["Footwear"],
    brand: "Bata",
  },
  {
    id: "f-449",
    url: "https://images.meesho.com/images/products/74345276/tnnnr_400.webp",
    title: "Sports fashionable shoes",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "3648",
    ratings: "3.4",
    category: ["Sports Shoes"],
    brand: "Relaxo",
  },
  {
    id: "f-4410",
    url: "https://images.meesho.com/images/products/352557717/ule9k_400.webp",
    title: "Korean style sandals",
    price: 424,
    deliveryStatus: "Free Delivery",
    reviews: "8628",
    ratings: "3.4",
    category: ["Sandals"],
    brand: "Liberty",
  },
  {
    id: "f-4411",
    url: "https://images.meesho.com/images/products/394243071/pd8ws_400.webp",
    title: "Kids Footwear",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "1336",
    ratings: "3.4",
    category: ["Kids", "Footwear"],
    brand: "Paragon",
  },
  {
    id: "f-4412",
    url: "https://images.meesho.com/images/products/522503238/unft9_400.webp",
    title: "Sports fashionable shoes",
    price: 224,
    deliveryStatus: "Free Delivery",
    reviews: "437",
    ratings: "3.4",
    category: ["Sports Shoes"],
    brand: "Bata",
  },
];

export const beautyProducts = [
  {
    id: "bp-551",
    url: "https://images.meesho.com/images/products/199994486/y67cv_400.webp",
    title: "Mens FaceWash",
    price: 324,
    deliveryStatus: "Free Delivery",
    reviews: "3756",
    ratings: "3.4",
    category: ["FaceWash"],
    brand: "LatiBlue",
  },
  {
    id: "bp-552",
    url: "https://images.meesho.com/images/products/406099925/av7oy_400.webp",
    title: "Massage ice Roller",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "346",
    ratings: "3.4",
    category: ["Massage"],
    brand: "MamaEarth",
  },
  {
    id: "bp-553",
    url: "https://images.meesho.com/images/products/14176377/09vvo_400.webp",
    title: "Vitamin-E Capsule",
    price: 324,
    deliveryStatus: "Free Delivery",
    reviews: "778",
    ratings: "3.4",
    category: ["Capsules"],
    brand: "DermaTouch",
  },
  {
    id: "bp-554",
    url: "https://images.meesho.com/images/products/295081509/mtxdo_400.webp",
    title: "MamaEarth Rice Facewash",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "566",
    ratings: "3.4",
    category: ["FaceWash"],
    brand: "MamaEarth",
  },
  {
    id: "bp-555",
    url: "https://images.meesho.com/images/products/186909137/jgrvh_400.webp",
    title: "Dermatouch facewash",
    price: 724,
    deliveryStatus: "Free Delivery",
    reviews: "664",
    ratings: "3.4",
    category: ["FaceWash"],
    brand: "DermaTouch",
  },
  {
    id: "bp-556",
    url: "https://images.meesho.com/images/products/434489685/zeeu7_400.webp",
    title: "Multani matti pack",
    price: 424,
    deliveryStatus: "Free Delivery",
    reviews: "453",
    ratings: "3.4",
    category: ["Face Pack"],
    brand: "LatiBlue",
  },
  {
    id: "bp-557",
    url: "https://images.meesho.com/images/products/401262974/olmla_400.webp",
    title: "Womens Combo Facepack",
    price: 324,
    deliveryStatus: "Free Delivery",
    reviews: "78565",
    ratings: "3.4",
    category: ["Face Pack"],
    brand: "DermaTouch",
  },
  {
    id: "bp-558",
    url: "https://images.meesho.com/images/products/279682111/kuhpx_400.webp",
    title: "Charcoal FaceMask",
    price: 284,
    deliveryStatus: "Free Delivery",
    reviews: "57567",
    ratings: "3.4",
    category: ["Face Mask"],
    brand: "MamaEarth",
  },
  {
    id: "bp-559",
    url: "https://images.meesho.com/images/products/408032566/ecuzx_400.webp",
    title: "Facial Hair removal kit",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "3648",
    ratings: "3.4",
    category: ["Kit"],
    brand: "LatiBlue",
  },
  {
    id: "bp-5510",
    url: "https://images.meesho.com/images/products/311047361/izpnn_400.webp",
    title: "Vitamin-C Facewash",
    price: 424,
    deliveryStatus: "Free Delivery",
    reviews: "8628",
    ratings: "3.4",
    category: ["FaceWash"],
    brand: "MamaEarth",
  },
  {
    id: "bp-5511",
    url: "https://images.meesho.com/images/products/311768960/5xb8w_400.webp",
    title: "Womens Perfume",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "1336",
    ratings: "3.4",
    category: ["Perfume"],
    brand: "LatiBlue",
  },
  {
    id: "bp-5512",
    url: "https://images.meesho.com/images/products/371537464/vrwoj_400.webp",
    title: "Facial Massage Kit",
    price: 224,
    deliveryStatus: "Free Delivery",
    reviews: "437",
    ratings: "3.4",
    category: ["Massage", "Kit"],
    brand: "DermaTouch",
  },
];

export const bags = [
  {
    id: "b-661",
    url: "https://images.meesho.com/images/products/194885424/hvchs_400.webp",
    title: "Womens Trendy HandBags",
    price: 324,
    deliveryStatus: "Free Delivery",
    reviews: "3756",
    ratings: "3.4",
    category: ["HandBags"],
    brand: "Lavie",
  },
  {
    id: "b-662",
    url: "https://images.meesho.com/images/products/392383953/azmdh_400.webp",
    title: "Girls Shoulder Bag",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "346",
    ratings: "3.4",
    category: ["Girls Shoulder Bags"],
    brand: "Baggit",
  },
  {
    id: "b-663",
    url: "https://images.meesho.com/images/products/195070537/vm077_400.webp",
    title: "Travel Bag",
    price: 324,
    deliveryStatus: "Free Delivery",
    reviews: "778",
    ratings: "3.4",
    category: ["Travel Bags"],
    brand: "Lino Perros",
  },
  {
    id: "b-664",
    url: "https://images.meesho.com/images/products/81412794/ivama_400.webp",
    title: "Mens Wallet",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "566",
    ratings: "3.4",
    category: ["Mens Wallet"],
    brand: "Hidesign",
  },
  {
    id: "b-665",
    url: "https://images.meesho.com/images/products/342686758/lzokz_400.webp",
    title: "Mens Shoulder Bag",
    price: 724,
    deliveryStatus: "Free Delivery",
    reviews: "664",
    ratings: "3.4",
    category: ["Mens Shoulder Bags"],
    brand: "Unique Sky",
  },
  {
    id: "b-666",
    url: "https://images.meesho.com/images/products/507928563/xcp4b_400.webp",
    title: "Travel Bag",
    price: 424,
    deliveryStatus: "Free Delivery",
    reviews: "453",
    ratings: "3.4",
    category: ["Travel Bags"],
    brand: "Lavie",
  },
  {
    id: "b-667",
    url: "https://images.meesho.com/images/products/359934952/9hv3q_400.webp",
    title: "Mens Shoulder Bag",
    price: 324,
    deliveryStatus: "Free Delivery",
    reviews: "78565",
    ratings: "3.4",
    category: ["Mens Shoulder Bags"],
    brand: "Baggit",
  },
  {
    id: "b-668",
    url: "https://images.meesho.com/images/products/375071525/h8ot5_400.webp",
    title: "Womens Trendy HandBags",
    price: 284,
    deliveryStatus: "Free Delivery",
    reviews: "57567",
    ratings: "3.4",
    category: ["HandBags"],
    brand: "Hidesign",
  },
  {
    id: "b-669",
    url: "https://images.meesho.com/images/products/4158256/1_400.webp",
    title: "Womens Trendy HandBags",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "3648",
    ratings: "3.4",
    category: ["HandBags"],
    brand: "Unique Sky",
  },
  {
    id: "b-6610",
    url: "https://images.meesho.com/images/products/167057949/r0i1s_400.webp",
    title: "Mens Wallet",
    price: 424,
    deliveryStatus: "Free Delivery",
    reviews: "8628",
    ratings: "3.4",
    category: ["Mens Wallet"],
    brand: "Lino Perros",
  },
  {
    id: "b-6611",
    url: "https://images.meesho.com/images/products/348772397/py4kn_400.webp",
    title: "Womens Trendy HandBags",
    price: 524,
    deliveryStatus: "Free Delivery",
    reviews: "1336",
    ratings: "3.4",
    category: ["HandBags"],
    brand: "Lavie",
  },
  {
    id: "b-6612",
    url: "https://images.meesho.com/images/products/450110661/afgdy_400.webp",
    title: "Womens Trendy HandBags",
    price: 224,
    deliveryStatus: "Free Delivery",
    reviews: "437",
    ratings: "3.4",
    category: ["HandBags"],
    brand: "Baggit",
  },
];
